name: Update Activity Graph

on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: Uszkido
          custom_title: Contribution Graph
          theme: github-dark
          hide_border: true
          output_path: dist/activity-graph.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          keep_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
